Add filter argument to Ringbuffer interface [API-1294]
hazelcast/hazelcast-nodejs-client pull request #1393
Opened 2022-10-08 13:21 UTC by fatihozer0

I am not sure if anything is right but can not say why it is wrong. I tried this on some other codes to try if it works and worked but not sure.

2022-10-13 16:22 UTC, srknzl commented
> I am not sure if anything is right but can not say why it is wrong. 

😄 What? 

Looks good, thanks

2022-10-13 16:22 UTC, srknzl submitted a review, later dismissed

2022-10-13 16:27 UTC, yuce requested changes
Could you port Java client's tests and add documentation and a code sample?

2022-10-13 23:22 UTC, srknzl commented
Adding a test may not be possible because server side code is needed. I don't know if we have a filter in the test jar. A code sample requires users to write java code in the server side. Not good.

You are right about the documentation. API documentation can be added.  Also there can be a small section about the filter in section https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/DOCUMENTATION.md#847-using-ringbuffer

2022-10-14 06:45 UTC, yuce commented
@srknzl The python client has two tests which uses the filter: https://github.com/hazelcast/hazelcast-python-client/blob/b8dd0d737ef976922311a8241e2a51b50e7ab3fa/tests/integration/backward_compatible/proxy/ringbuffer_test.py#L230 Could you guys check out them to see whether they can be ported to the Node.js client?

2022-10-14 09:18 UTC, srknzl commented
We can do and we should. It is in the test jar. 

https://github.com/hazelcast/hazelcast/blob/14ef0dbefa4a6fa00a50a8873aeea02ec6c3f5e4/hazelcast/src/test/java/com/hazelcast/client/test/PrefixFilter.java#L26

2022-10-14 12:14 UTC, fatihozer0 commented
Added a test which is not ported. I checked the links you shared. Gonna add documentations now

2022-10-24 15:34 UTC, srknzl commented on src/proxy/Ringbuffer.ts
> -    readMany(startSequence: number | Long, minCount: number, maxCount: number): Promise<ReadResultSet<E>>;
Can you add the API documentation?

2022-10-27 13:15 UTC, fatihozer0 commented on src/proxy/Ringbuffer.ts
> -    readMany(startSequence: number | Long, minCount: number, maxCount: number): Promise<ReadResultSet<E>>;
Done.

2022-10-27 14:14 UTC, srknzl approved these changes

2022-11-03 14:41 UTC, yuce approved these changes

2022-11-04 08:40 UTC, merged

2022-11-05 13:20 UTC, fatihozer0 commented
Continues on #1413