Add code sample for topic implementation [API-1522]
hazelcast/hazelcast-nodejs-client pull request #1421
Opened 2022-11-27 20:02 UTC by fatihozer0

2022-11-28 06:41 UTC, srknzl commented on code_samples/topic.js
> +
```suggestion
```

2022-11-28 06:44 UTC, srknzl requested changes
Seems fine when

2022-11-28 06:44 UTC, srknzl commented on code_samples/topic.js
> +} )().catch(err => {
```suggestion
})().catch(err => {
```

2022-11-28 06:44 UTC, srknzl commented on code_samples/topic.js
> +    topic.addMessageListener((message) => {
```suggestion
    await topic.addListener((message) => {
```

2023-03-17 19:17 UTC, fatihozer0 commented on code_samples/topic.js
> +
Done

2023-03-17 19:17 UTC, fatihozer0 commented on code_samples/topic.js
> +} )().catch(err => {
Done

2023-03-17 19:17 UTC, fatihozer0 commented on code_samples/topic.js
> +    topic.addMessageListener((message) => {
And done.

2023-03-17 19:20 UTC, fatihozer0 commented
Should I update Reliable Topic sample since we deprecated addMessageListener method?

2023-03-18 12:58 UTC, srknzl commented on code_samples/topic.js
> +        // shut down the client once the message is received
We can remove the listener here maybe.

2023-10-10 09:26 UTC, closed without merging